### ISSUE TITLE
Gradient search icon and back icon not showing on the GiphyViewController()

### ISSUE THREAD

**Issue by knawwxbackme** [Giphy/giphy-ios-sdk-ui-example#10]
The first time I ran I could see the search icon and back button once I started searching but now they aren't showing. I didnt change anything with the pod or anything else. The back button still works but I just can't see either. I use theme .light and .waterfall

**Comment by cgmaier** [comment]
Hey @knawwxbackme you closed this, I assume the issue has resolved itself, or you figured out a solution? If so, what was the solution? 

We've seen some weirdness with image assets not showing up in the past and will keep an eye out for this.
