### ISSUE TITLE
Still rendition types are not working

### ISSUE THREAD

**Issue by Vaberer** [Giphy/giphy-ios-sdk-ui-example#100]
I'm presenting a `GiphyViewController` with `originalStill` rentitionType and the it's not showing any results.
I also tried other still rendition types but it's always empty.

I gave another try with a `GiphyGridController` and setting rentitionType to still but the same.
I can confirm it worked when I was implementing it 2 months ago.

```
        let giphy = GiphyViewController()
        GiphyViewController.trayHeightMultiplier = 0.6
        giphy.renditionType = .originalStill
        giphy.mediaTypeConfig = [.stickers, .text, .emoji]
        giphy.delegate = self
        sender.present(giphy, animated: true)
```

**Comment by Vaberer** [comment]
I found that the tiles are there, I can also scroll but the still images aren't visible. If I change the rendition type to `.original`, it's working.

I'm attaching a screenshot.

![IMG_6B78E6869DDA-1](https://user-images.githubusercontent.com/8090436/94360679-76f55b00-00af-11eb-86e3-95c5f9e33180.jpeg)

**Comment by Vaberer** [comment]
Hello guys, I have one more important info, `still` rendition types don't work on Xcode 12. I have just built it in Xcode 11.7 and it's working. I Hope, it helps.

**Comment by cgmaier** [comment]
hey @Vaberer that's interesting! I'm curious to have a look at what's happening here with still renditions, though I'm also curious why you are choosing to go with stills. we normally recommend that developers do not adjust the `renditionType` property from the `fixedWidth` default. if performance is a concern, you may also try the `downsized` renditions.

**Comment by Vaberer** [comment]
Hello @cgmaier. Thank your reply. Currently, I'm just experimenting with static giphy images. If you need any further assistance, just let me know. I'm happy to help.

**Comment by Vaberer** [comment]
Hello @cgmaier, do you have any progress regarding the still rendition type?
Thanks for your time and reply

**Comment by Vaberer** [comment]
Hello, @cgmaier is there a change to fix this in a near future?
Thanks for your time.

**Comment by Vaberer** [comment]
Hey @cgmaier would you please have some time to take a look at rendering still types?
Many thanks!

**Comment by cgmaier** [comment]
hey @Vaberer apologies for the late reply. As GIPHY is all about being _animated_, still rendition support is not something we can provide at the moment. We think the content shines the best when it moves :) 
sorry we can't accommodate your request here.

**Comment by Vaberer** [comment]
I believe Giphy is all about images. The sdk says, it supports still images and it worked with Xcode 11.
Will you remove still rendition types from docs and remove it from sdk if you don't want to support stills?
Thanks
