### ISSUE TITLE
 'GPHClient' has no member 'search'

### ISSUE THREAD

**Issue by GRGBISHOW** [Giphy/giphy-ios-sdk-ui-example#105]
Couldn't find any other alternative APIs for search and trending in GIPHY 2. Any help? or Should I Implement GIPHY UI compulsorily?
Just upgraded to Xcode 12 and updated GIPHY 2 to support new compiler.
 
![Screen Shot 2020-10-01 at 18 36 27](https://user-images.githubusercontent.com/20558114/94811392-06cf3800-0415-11eb-91a8-fcb32acd1d8d.png)

**Comment by cgmaier** [comment]
this is a private method and we have no plans to make this method public unfortunately

please reach out to integrations@giphy.com for additional support
