### ISSUE TITLE
Translate 'Search GIPHY'

### ISSUE THREAD

**Issue by jetsekoopmans** [Giphy/giphy-ios-sdk-ui-example#108]
GIPHY SDK Version: 2.0.3

Is is possible to translate the text in the search bar? It is now always 'Search GIPHY'.

**Comment by cgmaier** [comment]
hey @jetsekoopmans I will look into this and get back to ya soon! thanks

**Comment by PasqualePuzio** [comment]
Any news on this? Thanks

**Comment by VittoriDavide** [comment]
It'd be excellent to have this feature

**Comment by PasqualePuzio** [comment]
> hey @jetsekoopmans I will look into this and get back to ya soon! thanks

@cgmaier is there a way to customize strings in GiphyViewController ?

Thanks

**Comment by cgmaier** [comment]
hey all, we've provided this option via a new property of `GiphyViewController` in v2.0.8
```
giphyViewController.placeholderText = "Search GIPHY"
```

**Comment by PasqualePuzio** [comment]
> hey all, we've provided this option via a new property of `GiphyViewController` in v2.0.8
> 
> ```
> giphyViewController.placeholderText = "Search GIPHY"
> ```

Thank you very much for this new property. Very much appreciated.

What about the Select button in the confirmation page? Can that title be customized?

Thank you

**Comment by cgmaier** [comment]
hi @PasqualePuzio sorry for the very long delay on this. the latest release includes customization for this string 
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.1.2
