### ISSUE TITLE
Set custom height of giphy view controller

### ISSUE THREAD

**Issue by h36ahmed** [Giphy/giphy-ios-sdk-ui-example#11]
I would like to customize the height of giphy view controller. Is that possible? Could you guys enable it? :)

**Comment by cgmaier** [comment]
hey @h36ahmed, thanks for reaching out! why exactly would you like to do this, or what experience are you hoping to enable with programatic height for the search drawer?

**Comment by h36ahmed** [comment]
So I have a video editing app and I have similar drawers like Giphy where I have them at a specific height so that user can add emojis or icons and see whats on the canvas. So for consistency and design purposes, I would like the drawer to have same height.

**Comment by cgmaier** [comment]
hey @h36ahmed interesting - makes sense. thanks for your reply. we'll note this and keep our eyes out for similar requests. i'll keep you posted if / when we can accommodate this use case. 

by the way, what's your app called? would love to check it out !

**Comment by h36ahmed** [comment]
Awesome! the app is called Veme.ly. We have yet to release the new version of the app with the new SDK and new UI that is similar to Giphy UI SDK. It would be awesome if your team loves Veme.ly and can give us a shout in your marketing campaigns or sites for using Giphy SDK.

**Comment by cgmaier** [comment]
hey @h36ahmed I've confirmed we can support this in our next release.

**Comment by h36ahmed** [comment]
Thank you! You guys are awesome!

**Comment by h36ahmed** [comment]
Awesome! You can close it.
