### ISSUE TITLE
Build Failed 2.0.4

### ISSUE THREAD

**Issue by binodav** [Giphy/giphy-ios-sdk-ui-example#111]
I'm using XCode 11.6

After upgrade to version 2.0.4, build failed with below error:

> Undefined symbols for architecture arm64:
>   "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
>       __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_GiphyUISDK in GiphyUISDK(GiphyAttributionViewController.o)
>      (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_GiphyUISDK)
>   "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
>       __swift_FORCE_LOAD_$_swiftCompatibility51_$_GiphyCoreSDK in GiphyCoreSDK(PingbackCollection.o)
>       __swift_FORCE_LOAD_$_swiftCompatibility51_$_GiphyUISDK in GiphyUISDK(GiphyAttributionViewController.o)
>      (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_GiphyUISDK, __swift_FORCE_LOAD_$_swiftCompatibility51_$_GiphyCoreSDK )
> ld: symbol(s) not found for architecture arm64

After downgrade to 2.0.2, it build successfully.

**Comment by cgmaier** [comment]
hey @binodav we're no longer supporting Xcode 11.6
