### ISSUE TITLE
 Showing All Messages Undefined symbol: __swift_FORCE_LOAD_$_swiftAVFoundation

### ISSUE THREAD

**Issue by chitvan832** [Giphy/giphy-ios-sdk-ui-example#114]
I am facing this issue in my project thus thought of trying in sample project
After installing the pod in the sample swift project I get the above error. I am using Xcode 12.0.1
<img width="1406" alt="Screenshot 2020-11-03 at 12 40 37 PM" src="https://user-images.githubusercontent.com/25215903/97957868-13f39400-1dd2-11eb-9e1e-3fd13700f97a.png">

**Comment by thorfroelich** [comment]
This issue seems to only manifest on Xcode 12.0. Xcode 12.1 works as expected.

**Comment by chitvan832** [comment]
@thorfroelich i updated my xcode but now i am seeing other error:
https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/115
