### ISSUE TITLE
Missing required module 'PINCache'

### ISSUE THREAD

**Issue by chitvan832** [Giphy/giphy-ios-sdk-ui-example#115]
In Xcode 12.1
After adding:
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.7/Giphy.podspec'
and installing i am seeing error `Missing required module 'PINCache'`. Please check screenshot.
![Screenshot 2020-11-03 at 6 01 56 PM](https://user-images.githubusercontent.com/25215903/97985723-aad64580-1dfe-11eb-9829-59fc4a0eb214.png)

This solution didn't work
https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/96#issuecomment-693639352

**Comment by cgmaier** [comment]
@chitvan832 do you have the `use_frameworks!` flag in your Podfile?

**Comment by chitvan832** [comment]
Adding `use_frameworks` solved the problem. Thanks

**Comment by dylmye** [comment]
I'm having this issue and adding `use_frameworks!` meant I could no longer run pod install / upgrade, I'd get CocoaPods/CocoaPods#7234 and the solution to that is to comment out use_frameworks!. Should I make a new issue?
![image](https://user-images.githubusercontent.com/7024578/102393833-cd987400-3fd0-11eb-9b5e-c3916ae906c9.png)

Thanks

**Comment by cgmaier** [comment]
hey @dylmye can you please confirm your version of Xcode as well as the GIPHY SDK version?

**Comment by dylmye** [comment]
Hiya

XCode 12.2 12B45b
Giphy SDK 2.0.9 (I think that's what you mean?)

Thank you

**Comment by dylmye** [comment]
So I made a new react native project with `npx react-native init`, added the react-native-giphy-keyboard repo with a fork I made with no changes so I can make changes to the project. So it should be reproducible.

If I use use_modular_headers! I get this instead:

<details><summary>Stack trace</summary>

```
info Found Xcode workspace "FOO.xcworkspace"
info Building (using "xcodebuild -workspace FOO.xcworkspace -configuration Debug -scheme FOO -destination id=...")

❌  /Users/.../Code/RnTest/FOO/ios/Pods/Headers/Public/glog/glog/logging.h:512:1: import of module 'glog.glog.log_severity' appears within namespace 'google'

#include "glog/log_severity.h"
                   ^~~~~~~

[... compile c logs...]

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/.../Library/Developer/Xcode/DerivedData/FOO-axlrpsnlogicwjcpssjljtrkzlrr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Folly.build/Objects-normal/x86_64/String.o /Users/.../Code/RnTest/FOO/ios/Pods/Folly/folly/String.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

</details>

Or if I do `pod 'Giphy', :modular_headers => true` I get this:

<details><summary>Stack trace</summary>

<pre>
info Found Xcode workspace "FOO.xcworkspace"
info Building (using "xcodebuild -workspace FOO.xcworkspace -configuration Debug -scheme FOO -destination id=...")

▸ Compiling EnumExtensions.swift

❌  /Users/.../Code/RnTest/FOO/node_modules/@.../react-native-giphy-keyboard/ios/EnumExtensions.swift:2:8: missing required module 'PINCache'

import GiphyUISDK
       ^


▸ Compiling RNGiphyKeyboard.swift

❌  /Users/.../Code/RnTest/FOO/node_modules/@.../react-native-giphy-keyboard/ios/EnumExtensions.swift:2:8: missing required module 'PINCache'

import GiphyUISDK
       ^

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'react-native-giphy-keyboard' from project 'Pods')

CompileSwift [...] /Users/.../Code/RnTest/FOO/node_modules/@.../react-native-giphy-keyboard/ios/EnumExtensions.swift:2:8: error: missing required module 'PINCache'
import GiphyUISDK
       ^
[...]

** BUILD FAILED **


The following build commands failed:
CompileSwift normal x86_64 /Users/.../Code/RnTest/FOO/node_modules/@.../react-native-giphy-keyboard/ios/EnumExtensions.swift
CompileSwift normal x86_64 /Users/.../Code/RnTest/FOO/node_modules/@.../react-native-giphy-keyboard/ios/RNGiphyKeyboard.swift
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
CompileSwift normal x86_64 /Users/.../Code/RnTest/FOO/ios/Pods/YogaKit/YogaKit/Source/YGLayoutExtensions.swift
</pre>

</details>

let me know if you need any other details

**Comment by dylmye** [comment]
Using the modular headers flag and [this solution](https://github.com/google/glog/issues/393#issuecomment-465974652) fixed the issue for me.
