### ISSUE TITLE
downloadAsset and gifByID closure don't called on timeout

### ISSUE THREAD

**Issue by Igor-Poltavtsev** [Giphy/giphy-ios-sdk-ui-example#116]
GPHCache.shared.downloadAsset and GiphyCore.shared.gifByID closure don't called on timeout (e.g. no connection).
Is it a bug or we can get this notification in some other way?
Thank you.

**Comment by emrdgrmnci** [comment]
I am trying to save giphy gif added image to camera roll but I can't save with GPHCache.shared.downloadAsset and GiphyCore.shared.gifByID closures. Do you try save gif added image to camera roll?

**Comment by cgmaier** [comment]
hey @Igor-Poltavtsev we made this adjustment with the latest release. let us know if you have any issues! 
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.1.2
