### ISSUE TITLE
How to set template as carousel.

### ISSUE THREAD

**Issue by chitvan832** [Giphy/giphy-ios-sdk-ui-example#117]
I cant find any documentation related to this.

**Comment by cgmaier** [comment]
hey @chitvan832 can you elaborate on what you're trying to achieve? 

in order to achieve a single-row horizontal layout, you can achieve this with the `GiphyGridController`

**Comment by chitvan832** [comment]
I am trying to achieve below look. This picture is taken from: [https://developers.giphy.com/docs/sdk#ios](url)
<img width="234" alt="Screenshot 2020-11-04 at 9 38 36 PM" src="https://user-images.githubusercontent.com/25215903/98135663-1b0bc680-1ee6-11eb-90d3-e91e062e1478.png">

**Comment by cgmaier** [comment]
I will make a note to my team to have this image removed as it's out of date - sorry about that !

you can implement this stye of design using the `GiphyGridControler`, however you will have to build your own search bar

**Comment by chitvan832** [comment]
Ohh is it. Anyway thanks for the quick response.
