### ISSUE TITLE
Where can I find a document of data collected by the giphy SDK? 

### ISSUE THREAD

**Issue by GalCohen** [Giphy/giphy-ios-sdk-ui-example#118]
Hi all. I'm sure some data is collected on usage, search results, etc.? Where can I find out what that is? Thanks!

**Comment by cgmaier** [comment]
hey @GalCohen, good question ! 

we don't currently provide analytics externally, however you are able to wire up your own events to capture how your users are interacting with features provided by the GIPHY SDK via the GiphyDelegate callbacks

**Comment by GalCohen** [comment]
Appreciate the quick response, @cgmaier . I meant data that *you* collect. Surely you collect some things, if only to track trending gifs - That sort of stuff. Need it for privacy, legal and management reasons but can't find exactly the right docs.

**Comment by cgmaier** [comment]
Thanks for clarifying! 

please shoot an email to integrations@giphy.com and our team can help answer any qs around data collection

**Comment by GalCohen** [comment]
Thank you!
