### ISSUE TITLE
Xcode 12.2 Build Error

### ISSUE THREAD

**Issue by VittoriDavide** [Giphy/giphy-ios-sdk-ui-example#119]
Hi,

I am building with Xcode 12.2, and Giphy version 2.0.7 and I am having the same issue https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/96 this time for swift version 5.3.1

Failed to build module 'GiphyUISDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

**Comment by JoeFerrucci** [comment]
I'm also getting both of these. Needs updates soon 😕 

```
Compiling for iOS 10.0, but module 'DeepDiff' has a minimum deployment target of iOS 13.0: /Users/someguy/Library/Developer/Xcode/DerivedData/someapp/Build/Products/Debug-iphonesimulator/DeepDiff/DeepDiff.framework/Modules/DeepDiff.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```
and
```
Failed to build module 'GiphyUISDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'
```

**Comment by cgmaier** [comment]
Hey there thanks for using GIPHY

the latest version of GIPHY SDK is v2.0.8

not sure why Xcode 12.2 swift compiler decided to break things. try increasing your deployment target or stick with Xcode 12.1 for the time being. 

I'm on vacation this week but hope to look at this soon

**Comment by cgmaier** [comment]
hi @JoeFerrucci @VittoriDavide please try: 
```
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.9/Giphy.podspec'
```  

have some ideas to prevent this in the future

**Comment by cgmaier** [comment]
@VittoriDavide can you confirm whether your error messages also noted 'DeepDiff' ?

**Comment by VittoriDavide** [comment]
Hi @cgmaier, I tried 

`pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.9/Giphy.podspec'
`

and is building okay on Xcode 12.2

**Comment by zintus** [comment]
2.0.9 worked for me on 12.2, thanks!

I'm not sure but maybe swift module stability should help with this?
