### ISSUE TITLE
Unable to set mediatypeconfig

### ISSUE THREAD

**Issue by paulxuca** [Giphy/giphy-ios-sdk-ui-example#12]
In an objective-c project:

```
GiphyViewController * gVC = [GiphyViewController init];
  
[gVC setMediaConfig GPHMediaTypeSticker];
```

or similar setters/methods do not work. Also the obj-c example does not do anything to this effect either.

**Comment by cgmaier** [comment]
Thanks for catching this @paulxuca ! I'll let you know when we fix this.

**Comment by cgmaier** [comment]
Hi @paulxuca [v1.0.2](https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v1.0.2) should fix this issue for you. just run `pod update` to update 

by the way, you'll need to do `[[ GiphyViewController alloc ] init ]` to properly create the `GiphyViewController, not just `[GiphyViewController init]`

thanks for you help, please let us know if you see anything else.

**Comment by paulxuca** [comment]
Thanks! 👍
