### ISSUE TITLE
Couldn\'t cast GPHMediaResponse to GPHMediaResponse during JSON response parsing

### ISSUE THREAD

**Issue by rfremont** [Giphy/giphy-ios-sdk-ui-example#124]
Hello,
Today we have this error when we use the method **GiphyCore.shared.gifByID**
**_Couldn\'t cast GPHMediaResponse to GPHMediaResponse during JSON response parsing_**
Our test id is l0HlC8RL28UGUAlmU
Server or SDK issue ?
Thanks

**Comment by cgmaier** [comment]
hey @rfremont are you still experiencing this issue? I'm not able to reproduce

**Comment by rfremont** [comment]
Yes no more issue today, I think it was an issue from the giphy server
