### ISSUE TITLE
Facing Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by sachinTechugo** [Giphy/giphy-ios-sdk-ui-example#128]
Getting this error using Xcode 11.3.1 
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/techugo/Library/Developer/Xcode/DerivedData/Example-fxmvjncsrzmvxlfwhamrjnnleewt/Build/Intermediates.noindex/Example.build/Debug-iphonesimulator/Example.build/Script-A717C15B7C7692959A9CCBBE.sh (in target 'Example' from project 'Example')
    cd /Users/techugo/Downloads/giphy-ios-sdk-ui-example-master-2/Swift
    /bin/sh -c /Users/techugo/Library/Developer/Xcode/DerivedData/Example-fxmvjncsrzmvxlfwhamrjnnleewt/Build/Intermediates.noindex/Example.build/Debug-iphonesimulator/Example.build/Script-A717C15B7C7692959A9CCBBE.sh

mkdir -p /Users/techugo/Library/Developer/Xcode/DerivedData/Example-fxmvjncsrzmvxlfwhamrjnnleewt/Build/Products/Debug-iphonesimulator/Example.app/Frameworks
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/techugo/Library/Developer/Xcode/DerivedData/Example-fxmvjncsrzmvxlfwhamrjnnleewt/Build/Products/Debug-iphonesimulator/DeepDiff/DeepDiff.framework" "/Users/techugo/Library/Developer/Xcode/DerivedData/Example-fxmvjncsrzmvxlfwhamrjnnleewt/Build/Products/Debug-iphonesimulator/Example.app/Frameworks"
building file list ... done
DeepDiff.framework/
DeepDiff.framework/DeepDiff
DeepDiff.framework/Info.plist
DeepDiff.framework/_CodeSignature/
DeepDiff.framework/_CodeSignature/CodeResources

sent 275524 bytes  received 98 bytes  551244.00 bytes/sec
total size is 275146  speedup is 1.00
/Users/techugo/Downloads/giphy-ios-sdk-ui-example-master-2/Swift/Pods/Target Support Files/Pods-Example/Pods-Example-frameworks.sh: line 131: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by cgmaier** [comment]
hi @sachinTechugo are you still experiencing this issue?
please update to the latest Xcode, if possible.
