### ISSUE TITLE
Filtering results by tags

### ISSUE THREAD

**Issue by paulxuca** [Giphy/giphy-ios-sdk-ui-example#13]
Hi there! 👋 

Wondering if there is a way to filter results by tags (i.e `sports`). I could do this with the Giphy API, but would love to be able to do this in the Giphy SDK.

Thanks!

**Comment by cgmaier** [comment]
hey @paulxuca, can you elaborate a bit? what sort of experience are you hoping to enable with tag filtering?

**Comment by paulxuca** [comment]
We would love to be able to show more relevant results only based on a search term. In our case, it's sports related gifs/stickers

**Comment by cgmaier** [comment]
gotcha ! unfortunately we likely can't support this in this SDK, but I'll pass your request along. what's your app if you don't mind me asking?
