### ISSUE TITLE
Release notes for iOS 2.1.0 are wrong

### ISSUE THREAD

**Issue by gogoslab** [Giphy/giphy-ios-sdk-ui-example#131]
In your release notes for iOS 2.1.0 you suggest to use the command
`pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.9/Giphy.podspec'` in the Podfile to use 2.1.0, but the link is related to 2.0.9.

I think it should be
`pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.0/Giphy.podspec'` to use 2.1.0 version

**Comment by cgmaier** [comment]
hey thanks so much @gogoslab : ) 
just fixed
