### ISSUE TITLE
Remove `user_target_xcconfig` settings

### ISSUE THREAD

**Issue by ergunkocak** [Giphy/giphy-ios-sdk-ui-example#133]
Blocker issue for the release:

What i have in console:

[!] Can't merge user_target_xcconfig for pod targets: ["Giphy", "mopub-ios-sdk", "Core", "MoPubSDK", "NativeAds"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

This started happening when i increased my minimum build target from 10.0 to 11.0

Solution: 
https://github.com/CocoaPods/CocoaPods/issues/3813
https://github.com/mopub/mopub-ios-sdk/pull/345

I guess you need to apply the same for your library.

Best

**Comment by cgmaier** [comment]
hey @ergunkocak can you try this and let me know? we've switched to .xcframework which will hopefully resolve this issue 

```
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.1.1-beta/Giphy.podspec'
```

official release planned for later this week

thanks!

**Comment by cgmaier** [comment]
these settings have been removed with this release:
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.1.1
