### ISSUE TITLE
GiphyGridController.numberOfTracks for iPad

### ISSUE THREAD

**Issue by chenshengzhi** [Giphy/giphy-ios-sdk-ui-example#134]
GiphyGridController.numberOfTracks is limited between 0 and 5.
So cells size is too big for iPad.
Please remove this limitation.
Thanks

**Comment by cgmaier** [comment]
thanks @chenshengzhi we'll include this change in the next release.

**Comment by chenshengzhi** [comment]
🎉 Thank you

**Comment by cgmaier** [comment]
hey @chenshengzhi this limitation is removed in the latest release 
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.1.2 
thanks!
