### ISSUE TITLE
Searchbar gestures questions and requests.

### ISSUE THREAD

**Issue by dolphinysaru** [Giphy/giphy-ios-sdk-ui-example#135]
Can I prevent the view from moving with the gesture of the searchbar?

**Comment by cgmaier** [comment]
hey @dolphinysaru - do you mean you would like to disable the pan gesture which lets users close the GIPHY search tray? 

can you offer more information why you would like to do this? 

thanks!

**Comment by dolphinysaru** [comment]
cgmaier

GiphyViewController is not present and applied as rootViewController of navigationController.
So, the screen should always be placed on top, but I think it is an unnecessary motion because move the screen with gestures.

**Comment by cgmaier** [comment]
hey @dolphinysaru we don't plan to support this use case at the moment. if you would like more control over how the UI is presented, you're welcome to use the `GiphyGridController` component instead of `GiphyViewController`. sorry we can't be of more help here!
