### ISSUE TITLE
Add GiphyViewController property to remove checkered background for stickers

### ISSUE THREAD

**Issue by everuribe** [Giphy/giphy-ios-sdk-ui-example#18]
See image from Swift example below. Would like the background to just be clear. 

Thank you!
![IMG_5629](https://user-images.githubusercontent.com/47759786/63569349-db013380-c52d-11e9-81b4-fa9e16bae8b2.jpg)

**Comment by cgmaier** [comment]
hey @everuribe did ya get a chance to try this out ? feel free to close this if it works for you!

**Comment by everuribe** [comment]
Works great! Thanks!
