### ISSUE TITLE
Giphy cannot be used with projects compiled in Xcode 11 w/ Swift 5.1

### ISSUE THREAD

**Issue by rsoffer** [Giphy/giphy-ios-sdk-ui-example#22]
`error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/.../Pods/Giphy/GiphySDK/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/x86_64.swiftmodule import GiphyUISDK`

**Comment by cgmaier** [comment]
hey @rsoffer , sorry for the inconvenience. we made a release for 5.1 which you can get [here](https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#swift-51) 

you must have the latest Xcode 11 (beta 7) for this to work. 

we'll push an official release to support 5.1 the second the official Xcode 11 is released.

**Comment by h36ahmed** [comment]
This works!

**Comment by dheeraj9022** [comment]
Compiled module was created by a newer version of the compiler: /Users/krishna/Desktop/2019 Current Projects/BabbleU/Pods/Giphy/GiphySDK/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by cgmaier** [comment]
@dheeraj9022 what Xcode version are you on?
