### ISSUE TITLE
Modify collectionView styling

### ISSUE THREAD

**Issue by laud** [Giphy/giphy-ios-sdk-ui-example#25]
I'm looking to modify the number of columns (to 3), cell size (to square), and cell contentMode (to aspectFit). 

What's the best way to make these modifications on `GiphyGridController`?

**Comment by cgmaier** [comment]
hey @laud ! we currently don’t support settings to modify cell aspect ratio and cell contentMode settings. I’ll note your request for my team and get back to you if anything changes.

**Comment by krishnagniyes** [comment]
@cgmaier I also need to provide similar feature in my project. Do you have any updates on this?

**Comment by cgmaier** [comment]
hey guys, ages later, but this is now supported ! please see my answer to this issue: https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/47
