### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by shial4** [Giphy/giphy-ios-sdk-ui-example#27]
Fatal error: Error writing to keychain - unhandledError(status: -25308): file /Users/chrismaier/Documents/GitHub/giphy-ios-sdk-ui/Carthage/Checkouts/giphy-ios-sdk-analytics/Source/GPHKeychain.swift, line 136

The app crashes constantly due to reason above.

**Comment by cgmaier** [comment]
hey @shial4 thanks for bringing this to our attention. we haven't been able to repro on our end unfortunately - could you provide some more details about when this happens and what device / simulator you're seeing this on?  

in the meantime, we pushed a hopeful fix for this in [v1.1.2](https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/1.1.2), which removes the [fatal error](https://developer.apple.com/documentation/swift/1538698-fatalerror)  so you should no longer see the crash 

hope this helps

**Comment by shial4** [comment]
I haven't been able to reproduce it myself, however, we do use Giphy now in our production app. Application was crash free, after introducing Giphy it dropped to 70% now. 

The error message above is what we have captured alone with: 
```
GiphyUISDK
$s17GiphyPingbacksSDK11GPHKeychainC5store3key5valueySS_10Foundation4DataVSgtFZyycfU_ + 412
```
and 
```
system_background_refresh
```

or second capture 
```

GiphyUISDK
__hidden#7722_ - Line 136
_hidden#7997_ + 136

GiphyUISDK
__hidden#617_ - Line 0
_hidden#831_
```

The last one have majority in number of crashes now. 
Please notice that crash is in regard to developer [Giphy SDK](https://developers.giphy.com/docs/sdk#ios).

Will let you know later next week. If this patch fixes it.

**Comment by cgmaier** [comment]
hey @shial4 hopefully the patch solves your issue 🙏  
 
just to be sure - are you following this best practice ? 
_Create a new GiphyViewController every time you want to show GIPHY (maintaining a reference to the same GiphyViewController object isn't necessary and can impact performance, and lead to unexpected results)_

btw for future reference, the latest & greatest docs will always be here: 
https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md

**Comment by shial4** [comment]
@cgmaier Thanks for your concern. We are following best practice.  
Anyway, will keep you posted.

**Comment by cgmaier** [comment]
hey @shial4 do you have any update on this?

**Comment by shial4** [comment]
Look like the crash numbers went down, however, I just did upload symbols. We should know shortly :)

**Comment by shial4** [comment]
Looks good. Crashes are gone. Thank you @cgmaier

**Comment by cgmaier** [comment]
Amazing, thanks @shial4 !
