### ISSUE TITLE
The Library Not working on Swift 5.0

### ISSUE THREAD

**Issue by KiranDhokale8118** [Giphy/giphy-ios-sdk-ui-example#28]
Hello , I am using it but it cannot work on Swift 5.0 , Please provide the solution

**Comment by cgmaier** [comment]
hey @KiranDhokale8118 we no longer support Swift 5.0 - please update to the latest Xcode 11

**Comment by cgmaier** [comment]
i'm gonna go ahead and close this @KiranDhokale8118
