### ISSUE TITLE
didDismiss not being called when "swiped down"

### ISSUE THREAD

**Issue by landnbloc** [Giphy/giphy-ios-sdk-ui-example#29]
When the ui resize bar right above the search bar is swiped down causing the view controller to go away for some reason "didDismiss" is not called. Is there another method I should be implementing? I'm using an Iphone 11

**Comment by cgmaier** [comment]
hey @landnbloc thanks for catching this - will let you know we fix it! hopefully not a blocker for you.

**Comment by landnbloc** [comment]
hey @cgmaier thank you!

**Comment by cgmaier** [comment]
hey @landnbloc this should be fixed now with [v1.1.3](https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v1.1.3)! thanks again for your help pointing this out.

**Comment by landnbloc** [comment]
Awesome! appreciate it. Working well except when it's dismissed in this fashion and reopened the trayHeightMultiplier seems to be cut in half and gets progressively lower

**Comment by landnbloc** [comment]
I was using the same instance, thanks for your help
