### ISSUE TITLE
Channel feed/list in search results

### ISSUE THREAD

**Issue by timurbeg** [Giphy/giphy-ios-sdk-ui-example#30]
Original GIPHY app has horizontal channel feed(between GiFs/Stickers/Text segment control and collection view) as a part of search results. 
But GPHListMediaResponse object doesn't contain any channel related data.
Is there separate API call for the channel list?
Is it possible to include channels array into search API response?

**Comment by cgmaier** [comment]
hi @timurbeg good question.  unfortunately channel-related APIs are not publicly available - we reserve channel search for the GIPHY app : )  

sorry we can't help in this case
