### ISSUE TITLE
Video Edit 

### ISSUE THREAD

**Issue by KiranDhokale8118** [Giphy/giphy-ios-sdk-ui-example#32]
Please provide the demo to add the giphy on video and also after export the video it must contain the Giphy with animatable as we added previously.

**Comment by cgmaier** [comment]
hey @KiranDhokale8118, we don't have sample code for this use case unfortunately.  

there's a lot of ways to go about adding stickers / gifs to videos. You can also learn about SceneKit / AVFoundation (Apple APIs). I'm also big fan of GPUImage3. 

sorry we can't help more with this ! good luck

**Comment by adxworld** [comment]
Hey can you guide me on how to do this in a videoComposition in AVExportSession. I would really really appreciate pointers and I am really unable to get an idea. I dont want you to give me the code. But please point me in right direction a bit more detailed that the previous answer 

I even have a question posted here : https://stackoverflow.com/questions/65575445/avexportsession-add-uiview-with-gifs-and-drawings-on-a-video
