### ISSUE TITLE
Apple would reject apps with SDK using UIWebView

### ISSUE THREAD

**Issue by fkhasib** [Giphy/giphy-ios-sdk-ui-example#33]
we get this error from Apple for using Giphy iOS sdk, can you please update to  WKWebView so we can stay in compliance?

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. | ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
-- | --
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by cgmaier** [comment]
hey @fkhasib thanks for reaching out. what leads you to believe the GIPHY SDK is the source of this issue? I've searched through the codebase and don't see any references to `UIWebView`

**Comment by fkhasib** [comment]
@cgmaier Thank you for responding, I ran the following command and I got this as a result that comes from Giphy iOS sdk, other than we got this error only after adding Giphy sdk
`nm myapp | grep UIWeb
for framework in Frameworks/*.framework; do
  fname=$(basename $framework .framework)
  echo $fname
  nm $framework/$fname | grep UIWeb
done
`
see the result 

<img width="746" alt="Screen Shot 2019-09-30 at 11 56 07 AM" src="https://user-images.githubusercontent.com/4357228/66324512-767e1600-e8da-11e9-8033-431c376c42c0.png">

**Comment by cgmaier** [comment]
this is super helpful. thanks @fkhasib !
to clarify, did Apple entirely block you from submitting, or was it just a warning?

**Comment by fkhasib** [comment]
@cgmaier I am pretty familiar with their warnings, but unlike the warning they provide this one seems a blocker, we still havent submitted our app but the language as you can read is clear regarding this, my assumption is all this after iOS 13 release
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by cgmaier** [comment]
thanks so much for flagging this @fkhasib! this must be new. we're going to try to get a release out with a fix asap

**Comment by fkhasib** [comment]
@cgmaier I can confirm its new, as I had the sdk for a month and it showed up two weeks ago, Thank you for taking care of this, looking forward!

**Comment by cgmaier** [comment]
hey @fkhasib ! hoping [v1.1.3](https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v1.1.3) will fix this issue.

**Comment by fkhasib** [comment]
@cgmaier thank you so much, I will update you as soon its available at cocoa pods, probalbly later tonight or early morning! thanks for the quick turn around

**Comment by fkhasib** [comment]
@cgmaier I can confirm, that release fixed the issue, thanks for the quick release!

**Comment by cgmaier** [comment]
thank you @fkhasib !!
