### ISSUE TITLE
Getting image from PINCache

### ISSUE THREAD

**Issue by SolorzanoJose** [Giphy/giphy-ios-sdk-ui-example#36]
Having to download the data from the media URL after successfully picking a gif is a painful UX.

I'd like to know what key you're using to cache media through PINCache that way I can just fetch it myself and avoid having to download the file data.

Thanks

**Comment by cgmaier** [comment]
hey @SolorzanoJose thanks for the feedback 

if you want to grab the image that's already loading in the grid, you can do the following: 
```
func didSelectMedia(giphyViewController: GiphyViewController, media: GPHMedia) {

     guard let url = media.url(rendition: giphyViewController.renditionType, fileType: .webp) else { return }
     GPHCache.shared.downloadAsset(url) { (image, error) in
            // image is GiphyYYImage based on YYImage
     }
``` 
you can also set a `GPHMedia` directly on a `GPHMediaView` like so: 

```
mediaView.setMedia(media, rendition: giphyViewController, shouldQueueOriginalRendition: false)
``` 
let me know if this helps! maybe should add to the documentation

**Comment by cgmaier** [comment]
Gotcha! can you try accessing the `GiphyYYImage`'s data via `animatedImageData` property ?

**Comment by cgmaier** [comment]
(sorry i replied without fully processing your comment)

that's a good question - i'm honestly not sure why that wouldn't work. perhaps `PINCacheAnimatedImage` doesn't support the `webp` format? 

also curious about your concern about using `GiphyYYImage`?  `GiphyYYImageView` should be nice n performant and doesn't have any GIPHY branding on it

**Comment by SolorzanoJose** [comment]
@cgmaier I'm using texture in my app, using something ImageView based would neglect the benefits

I tried .gif format but it still doesn't work, looks like the main gif libraries including SwiftyGif cannot use the data we get from this method (animatedImageData)

I basically just want the raw gif data that I can use myself

**Comment by cgmaier** [comment]
ah hmm, are you seeing that `animatedImageData` at least contains data and is not empty / nil?  i'm not too familiar with Texture. `GiphyYYImage` is based on [YYImage](https://github.com/ibireme/YYImage)

**Comment by SolorzanoJose** [comment]
Yup, the data is not empty or nil but it isn't working with other mainstream gif libraries, I will take a look at that library but it seems it does something internally that modifies the gif data

**Comment by SolorzanoJose** [comment]
Hmmm is YYImage not included in the dependencies for the SDK? I'm not able to import it (I used the SDK through cocoapods), this is really complicated to debug closed source

**Comment by SolorzanoJose** [comment]
I'm closing this because I found a way around it.

**Comment by SolorzanoJose** [comment]
Reopening this real quick for a last question.

@cgmaier adding unit tests to this is kinda complicated cause everything is private and of course its closed source but I have one question that maybe you can help me with:

What triggers the selection of a gif in the collection view?

I tried triggering selectItem(at: IndexPath) but that's not really working, is it a tap in a subview of the cell? thanks

**Comment by cgmaier** [comment]
hey @SolorzanoJose sorry for the late reply. that's correct - we respond to a tap gesture in the cell. I'm not sure if you can properly hook into this but we can consider exposing this function as public in a future release for the purpose of supporting unit tests.

**Comment by ravi-devstree** [comment]
@SolorzanoJose Please post your solution so others can use it.

**Comment by ravi-devstree** [comment]
> I'm closing this because I found a way around it.

Please post your solution so others can use it.
