### ISSUE TITLE
GiphyCoreSDK.GPHMedia aspectRatio

### ISSUE THREAD

**Issue by annaharri89** [Giphy/giphy-ios-sdk-ui-example#38]
We are getting a crash when we try to access a media's aspect ratio. We are using version 1.1.0 Has this bug been fixed in version 1.1.1? We can't upgrade to that version at the moment because we are not able to upgrade to Xcode 11 (we have a deprecated dependency that can't run on Xcode 11). Is there anything we can do to fix this bug on version 1.10?

**Comment by cgmaier** [comment]
hey @annaharri89 thanks for reaching out !

we've actually fixed a number of things since 1.1.0, any chance you can upgrade? 

i don't see how simply accessing the `GPHMedia`'s aspect ratio would cause a crash. are you seeing that it is returning 0's and that's in turn causing a crash somewhere else in your code? more info on this would be helpful ! 

do you recall my answer to the last issue you opened, a while back? 
https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/9 perhaps having another look at that could be helpful

**Comment by annaharri89** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/16767360/67709844-2bb16480-f995-11e9-9336-fae39d3eb1c6.png">
The highlighted line of code is where it crashes

And this is the crash
<img width="553" alt="image" src="https://user-images.githubusercontent.com/16767360/67709893-47b50600-f995-11e9-9ccf-21e06a57db82.png">

I do remember your answer, and we've actually implemented the GiphyCore.shared.gifByID method in order to get the aspect ratio.

As for upgrading to the newest version of the giphy sdk, the docs show that you need to upgrade to Xcode 11 in order to upgrade to 1.1.1 of the giphy sdk
<img width="324" alt="image" src="https://user-images.githubusercontent.com/16767360/67710104-ae3a2400-f995-11e9-826c-ca7941cc2dd8.png">

We cannot currently upgrade to Xcode 11 because we have a dependency that can't work on Xcode 11. We are very close to being able to remove that dependency, at which point we'll be able to upgrade to Xcode 11 and upgrade our giphy sdk, but that could still be a few days away. Is there anything we can do in the mean time to get around this crash?

**Comment by cgmaier** [comment]
gotcha, that's weird. anyway can you try: 
```
let width = media.images?.original?.width
let height = media.images?.original?.height
```

as an alternative way of obtaining the image dimensions

**Comment by annaharri89** [comment]
@cgmaier 

That fixed the crash, but now the sent gifs are not loading and the gif picker has these rainbow loading dots permanently,  no gifs load in the gif picker. Do you know why that would be happening?

**Comment by annaharri89** [comment]
Is it because we're on an old version?

**Comment by cgmaier** [comment]
hmm that's odd, is it possible it's a connection issue?
