### ISSUE TITLE
Update for Swift 5.1.2

### ISSUE THREAD

**Issue by wvdk** [Giphy/giphy-ios-sdk-ui-example#39]
Cannot build with the Giphy pod on Xcode Version 11.2 (11B52)

<img width="649" alt="Screen Shot 2019-10-31 at 2 12 33 PM" src="https://user-images.githubusercontent.com/13443286/67986534-80005280-fbe8-11e9-839d-f944a2c8bd8a.png">

**Comment by zeusent** [comment]
I have the same issue :( Is this going to be a blocking thin every time Xcode get's updated?

<img width="571" alt="Screenshot 2019-11-01 at 02 56 44" src="https://user-images.githubusercontent.com/777591/67995477-431d7580-fc53-11e9-909c-5b2859fb7ad7.png">

**Comment by hanjinghe** [comment]
I also have the same issue. I really need new version fixed issue for publishing to users ASAP

**Comment by zeusent** [comment]
Since Swift 5 was supposed to fix these kind of issues I was intrigued why we see this. I think I found the answer here:

https://stackoverflow.com/a/58656323/831838

Maybe this is something that can be done for Giphy as well? Right now my project is broken because of it and I have to explain to my employer that there's nothing I can do until a new update for Giphy is being released. If we could go around this in the future would be awesome!

**Comment by cgmaier** [comment]
hey i'm really sorry for the trouble - going to get a fix out ASAP and do my best to make sure this doesn't happen again

**Comment by zeusent** [comment]
Nice @cgmaier ! Your quick replies and actions are most welcomed as always! Thanks a lot!

**Comment by cgmaier** [comment]
hey so i'm having some trouble getting the update `1.1.6` via `pod update` for some reason. i successfully submitted the update to Cocoapods via `pod trunk push` - i wonder if there's a bit of a delay though it's always been pretty quick in my experience. i'll keep on trying and troubleshooting.
 in the meantime you can get the latest version by explicitly referencing the podspec location explicitly in your Podfile like so  
```
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.1.6/Giphy.podspec' 
```

this version is just a quick hot fix to support the latest xcode / swift version. we're going to follow up with another update soon with long term fix for swift version compatibility

**Comment by cgmaier** [comment]
ah sorry it should be `1.1.5` 
https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.1.5/Giphy.podspec

**Comment by zeusent** [comment]
Yup, that did it! Awesome! I'm unblocked, awesome! 👍

**Comment by cgmaier** [comment]
okay, great. so weird that there was such a long delay before `pod update` got the latest version. 

i'll keep you updated on the swift version compatibility here & hopefully push another release later today.

**Comment by cgmaier** [comment]
a bit of an update if anyone is concerned - i've fixed this issue in GIPHY SDK but still waiting on the DeepDiff dependency to push a release with this fix 

https://github.com/onmyway133/DeepDiff/issues/51

**Comment by AlexClarkQP** [comment]
I just tried to integrate the API into my new product and I'm also getting "Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler". I notice the last comment was a month ago. Is there any update for this (I hope because this API is awesome)?

**Comment by cgmaier** [comment]
hey @AlexClarkQP what version of the SDK are you on? 

you can see the latest releases here:  
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases

**Comment by cgmaier** [comment]
@AlexClarkQP swift compatibility has proven tricky unfortunately - it's a goal for the start of the new year. in the meantime i can ensure i'll always make sure the latest Xcode is supported 

however, i have verified the latest version of the SDK `v1.1.8` (actually compiled with Swift 5.1.2 i believe) supports the latest Xcode 11.3. just run `pod update` to get the latest

**Comment by AlexClarkQP** [comment]
Perfect, I was using a beta version of Xcode but if you'll always support the latest then I'll try not to get ahead of things. I tested on the non-beta and all good. Thank you!

**Comment by cgmaier** [comment]
As a test, I just built the SDK with the Xcode 11.1 command line tools (Swift 5.1), and was able to install and run the resulting SDK framework in Xcode 11.3 (Swift 5.1.3), so I'm hoping we've achieved module stability as of Giphy v1.1.8. However, I did notice that it was necessary to include the `use_frameworks!` flag in the Podfile. 

When you commented, you mentioned Swift 5.1 which leads me to believe you may not have been on the latest version of the Giphy SDK - is this possible?

**Comment by AlexClarkQP** [comment]
Yes, entirely possible since I’ve tried quite a few things and got a little lost in the process.

**Comment by cgmaier** [comment]
gotcha! well since i'm confident that we're good for future versions (and certainly good for swift 5.1.2 which this issue points out), i'm going to ahead and close this issue. obviously if a new Xcode / Swift version breaks thing we'll push an update as quick as possible.
