### ISSUE TITLE
Compile error Swift 4.2

### ISSUE THREAD

**Issue by codeplotter** [Giphy/giphy-ios-sdk-ui-example#41]
I have Xcode 11.2 and just installed the pod.  I initially had an error where it could not find GIPHYUISDK in the screen controller file when I was importing it.  Please note that this is a keyboard extension inside a wrapper app.  After adding $(SRCROOT) to the framework search paths for project and targets, now the compiler is giving the error:

"<unknown>:0: error: missing required module 'OMSDK_Giphy'
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/GiphyUISDK-Swift.h" "

I have done some searching but have not found the answer yet.  Please advise if possible!  Let me know if you would like more compiler data.

**Comment by codeplotter** [comment]
<img width="748" alt="Screen Shot 2019-11-05 at 7 46 37 PM" src="https://user-images.githubusercontent.com/25725009/68261271-2a231480-0005-11ea-8bec-b57466e726f4.png">

**Comment by cgmaier** [comment]
hey @codeplotter the GIPHY UI SDK won't work inside extensions
