### ISSUE TITLE
Compiler Warning

### ISSUE THREAD

**Issue by kriglz** [Giphy/giphy-ios-sdk-ui-example#42]
<img width="1061" alt="Screen Shot 2019-11-19 at 2 55 23 PM" src="https://user-images.githubusercontent.com/28742724/69193926-c60c5000-0adc-11ea-8c1e-d141ba1cc7ae.png">

**Comment by cgmaier** [comment]
hi @kriglz thanks for opening this issue : ) can you please let me know if this warning is still present in the newly released 1.1.7?

**Comment by kriglz** [comment]
> hi @kriglz thanks for opening this issue : ) can you please let me know if this warning is still present in the newly released 1.1.7?
Hi @cgmaier, it's not present anymore. Thanks :)

**Comment by cgmaier** [comment]
thank you for confirming @kriglz !
