### ISSUE TITLE
How to modify GiphyGridController?

### ISSUE THREAD

**Issue by krishnagniyes** [Giphy/giphy-ios-sdk-ui-example#47]
I'm looking to modify the number of columns (to 3), cell size (to square), and cell contentMode (to aspectFit).

What's the best way to make these modifications to GiphyGridController?

**Comment by krishnagniyes** [comment]
Any updates?

Thanks

**Comment by cgmaier** [comment]
Hey there, ver sorry about the late reply @krishnagniyes -- we're in the process of working on this and will get back to you when we have an update

**Comment by cgmaier** [comment]
hey @krishnagniyes sorry for such a late reply! 

we've updated the [docs](https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#grid-only-and-the-giphygridcontroller-setup) to explain everything having to do with the grid. 

you can achieve number of columns via 
```
gridController.numberOfTracks = 3
```
and fixed size cells with: 
```
gridController.fixedSizeCells = true 
``` 
`fixedSizeCells` option only works for stickers not GIFs. the content mode is always aspect fit. 

hope this helps!

**Comment by laud** [comment]
Looks great @cgmaier! I think there is an issue with `gridController.cellPadding = 10.0` in that the padding is not respected. Should I open another ticket for this?

**Comment by cgmaier** [comment]
thanks @laud ! sorry about the confusion  

the padding has a max limit of 12.0 pts, and so if it's set to a value higher than this, it does nothing.  

 we will document this properly, print some logs if it's set to a higher value, and can probably expand it a bit in our next release
