### ISSUE TITLE
Enable bitcode for GiphyUISDK

### ISSUE THREAD

**Issue by zeusent** [Giphy/giphy-ios-sdk-ui-example#5]
I know this repository is only an example repo but I cannot find any issue or feature tracker for GiphyUISDK.

I'm using this SDK in an app I'm building and I was curious if there's maybe a way for you guys to turn on Bitcode for iit. From the multitude of 3rd party frameworks I'm using this is the only one currently not supporting this.

Thanks!

**Comment by cgmaier** [comment]
Hey, thanks for reaching out. This is a great place to open issues around the Giphy UI SDK!  

I just published an update with Bitcode in version v1.0.1. Let us know if this solves your problem and please reach out if you notice anything else : ) 

Chris

**Comment by zeusent** [comment]
Hey Chris! Thanks for your fast reply. I think this would've worked. The problem is that since yesterday Apple just released Xcode 11 beta 4 which now uses Swift 5.1 and now `GiphyUISDK` doesn't work at all anymore. I get this compiler error now:

`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /...PATH-TO-MY-PROJECT.../Pods/Giphy/GiphySDK/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/arm64.swiftmodule`

Any way to get a temp branch for this?

**Comment by cgmaier** [comment]
Hey @zeusent I'll look into to 5.1 compatibility but can't make any promises we'll get to this in the short term. We'll support Xcode 11 and corresponding Swift versions in advance of the official release later this year.

**Comment by cgmaier** [comment]
Going to close this issue if that's alright, but will comment here to keep you in the loop about any news of Swift 5.1

**Comment by zeusent** [comment]
Awesome! Thanks a lot!

**Comment by roderickhodgson** [comment]
Hello. Joining the conversation to find out if there's any more news on support for Swift 5.1, now that Xcode 11 has been released?

Thanks!

**Comment by zeusent** [comment]
Yup, version 1.1.1 should do the trick

**Comment by roderickhodgson** [comment]
Thanks zeusent. I didn't look closely enough, I thought I had already updated to 1.1.1, but a podspec had kept me at 1.0.1 and I didn't notice. Thanks.
