### ISSUE TITLE
Methods publicly accessible

### ISSUE THREAD

**Issue by alexmomotiuk** [Giphy/giphy-ios-sdk-ui-example#50]
Why the search and trending functions are not publicly accessible now ?

**Comment by cgmaier** [comment]
hey @alexmomotiuk ! We're making some changes to how the SDK is structured. Our long term goal is to serve all users of the SDK via our UI components, which we hope will ultimately be flexible enough to handle the vast majority of use cases. 

Feel free to reach out to sdk@giphy.com with the name of your app and they can work with you to find the best solution for you.
