### ISSUE TITLE
How to get GiphyYYImage synchronously in 1.2.2 version?

### ISSUE THREAD

**Issue by alexanderkhitev** [Giphy/giphy-ios-sdk-ui-example#53]
Hi everyone! Before we used this method for getting GiphyYYImage from cache 

`guard let yyImage = GPHCache.shared.pinCache.object(forKey: cacheKey) as? GiphyYYImage else { return nil }
`

as I understand we can use completion handler in 1.2.2 version, but do we have opportunity to get GiphyYYImage synchronously?

Thanks!

**Comment by cgmaier** [comment]
hey @alexanderkhitev !! i assume you figured it out? 

the completion handler will return right away if it's a hit, or a little longer to download if it's a miss. i thought a single completion block was a nice way of handling both cases, but maybe we can improve this?
