### ISSUE TITLE
How to resolve this syntax issue?

### ISSUE THREAD

**Issue by manjureddy48** [Giphy/giphy-ios-sdk-ui-example#54]
let giphy = GiphyViewController().   'GiphyViewController' cannot be constructed because it has no accessible initializers

**Comment by cgmaier** [comment]
hmm there must be an issue with how you're linking the Giphy SDK. lets resolve in the other issue you opened

**Comment by cgmaier** [comment]
im going to close this as i believe it's just a result of the other issue you opened
