### ISSUE TITLE
How to fix this issue Could not build module 'GiphyUISDK'?

### ISSUE THREAD

**Issue by manjureddy48** [Giphy/giphy-ios-sdk-ui-example#55]
@import GiphyUISDK;  Could not build module 'GiphyUISDK'

**Comment by cgmaier** [comment]
hey @manjureddy48, what Xcode and GIPHY SDK versions are you using? 

if you installed the SDK via Cocoapods, be sure to open the resulting workspace file rather than the project file

**Comment by manjureddy48** [comment]
> hey @manjureddy48, what Xcode and GIPHY SDK versions are you using?
> 
> if you installed the SDK via Cocoapods, be sure to open the resulting workspace file rather than the project file

We are using Xcode 11.1 and laterst Giphy sdk install via cocoapod

**Comment by cgmaier** [comment]
are you able to upgrade to the latest official Xcode release?

**Comment by cgmaier** [comment]
hey @manjureddy48 i wanted to follow with you and ask if it's okay to close this issue. thanks!

**Comment by cgmaier** [comment]
hey @manjureddy48 i think the issue may be fixed by ensuring `use_frameworks!` is added to your Podfile
