### ISSUE TITLE
Hide keyboard when scrolling

### ISSUE THREAD

**Issue by MarcoCadei** [Giphy/giphy-ios-sdk-ui-example#56]
Hi all,

is it possible to hide the keyboard when the user scrolls through the gifs?
I would like for my users to see the view controller full screen, search with the desired query and then hide the keyboard if they start scrolling so that they can see more gifs.

Is there an option for this? A callback I can listen to through a delegate?

**Comment by cgmaier** [comment]
hey @MarcoCadei ! that's a great idea - we can add a "userDidScroll" callback to the `GPHGridDelegate` to handle your case. I will keep you in the loop when we add this change.

**Comment by MarcoCadei** [comment]
> we can add a "userDidScroll" callback to the GPHGridDelegate to handle your case

That would be super cool! I'll wait for more news 🚀

**Comment by cgmaier** [comment]
hey @MarcoCadei i went ahead and made this improvement with v1.2.4 

let me know if you have any issues with the update. 

```
@objc optional func didScroll(offset: CGFloat)
```

**Comment by MarcoCadei** [comment]
Thank you, works like a charm! 🙏
