### ISSUE TITLE
Module 'PINCache' not found

### ISSUE THREAD

**Issue by PureBreadd** [Giphy/giphy-ios-sdk-ui-example#57]
I am running Xcode 13.3.1 and installed the Giphy 1.2.2 SDK. When I go to import 'GiphyUISDK' to a view controller, I get the following Swift Compiler Error:

Module 'PINCache' not found
<unknown>:0: error: could not build Objective-C module 'GiphyUISDK'

Note: I do see the PINCache folder in my Pods folder and when I installed/updated the Cocoapods, the terminal read:
Installing DeepDiff (2.3.1)
Installing Giphy (1.2.2)
Installing PINCache (2.3)
Installing libwebp (1.1.0)

... so it looks like PINCache was downloaded but for some reason the GiphyUISDK can't find it.

**Comment by cgmaier** [comment]
hey @PureBreadd - that's strange. are you able to run the example app in this repo?

**Comment by PureBreadd** [comment]
@cgmaier 
- When I open the example app, I run into the error "Unable to load contents of file list: '/Target Support Files/Pods-Example/Pods-Example-frameworks-Debug-input-files.xcfilelist'". This seems like a different issue, so I wasn't going to mention it.
- Also, I previously used an older version of the GiphySDK in another project (1.0.9 I think), but that version isn't compatible with the new swift compilers so I am forced to use the newer version.. which is the original issue.
Thanks

**Comment by cgmaier** [comment]
hey @PureBreadd - that's strange. to clarify, can you please share what your Podfile looks like? You can replace your app name if you'd like.

**Comment by PureBreadd** [comment]
@cgmaier, thanks for the quick response. My entire podfile is below. (I updated to Giphy 1.2.4 this morning and tried uninstalling/reinstalling the SDK and it didn't not fix the problem.)

target 'AppNameHere' do
pod 'Giphy'
end

Below are screenshots of the error message.

<img width="821" alt="Screen Shot 2020-03-20 at 2 55 53 PM" src="https://user-images.githubusercontent.com/44950578/77197507-aea99780-6abb-11ea-8b98-63332a210479.png">
<img width="812" alt="Screen Shot 2020-03-20 at 2 57 05 PM" src="https://user-images.githubusercontent.com/44950578/77197513-b0735b00-6abb-11ea-9b40-c9edd9f21b10.png">

**Comment by cgmaier** [comment]
hey @PureBreadd sorry about that ! can you try adding the `use_frameworks!` flag to your Podfile? 
```
use_frameworks!
target "Example" do 
pod 'Giphy'
end 
```

**Comment by PureBreadd** [comment]
@cgmaier that worked fyi! Cheers!
