### ISSUE TITLE
 Binary XML file line #33: Binary XML file line #33: Error inflating class com.giphy.sdk.ui.views.GPHMediaView

### ISSUE THREAD

**Issue by iehsan77** [Giphy/giphy-ios-sdk-ui-example#61]
getting the following error with

<com.giphy.sdk.ui.views.GPHMediaView
android:id="@+id/gifViewAnimated"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:layout_marginTop="16dp"
android:layout_marginEnd="24dp"
android:elevation="4dp"
android:scaleType="fitCenter"
app:layout_constraintEnd_toEndOf="parent"
app:layout_constraintTop_toTopOf="parent"
tools:srcCompat="@tools:sample/avatars" />

App crash with the following error

Process: com.example.smeschat, PID: 14226
android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class com.giphy.sdk.ui.views.GPHMediaView
Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.giphy.sdk.ui.views.GPHMediaView
Caused by: java.lang.reflect.InvocationTargetException

**Comment by cgmaier** [comment]
hey @iehsan77 please open an issue in our Android repo here: https://github.com/Giphy/giphy-android-sdk-ui-example
