### ISSUE TITLE
Creating GPHMediaView from a URL does not work

### ISSUE THREAD

**Issue by Kalvin126** [Giphy/giphy-ios-sdk-ui-example#62]
So I have a case where I save the `url` of a `GPHMedia` and when I need to load it again, I want to  pass it back to a `GPHMediaView` to load it via that `url`.

I see there is a `func loadAsset(at url: String, queueOriginalRendition: Bool = false)` on `GPHMedia`. When I use it, it only shows a white screen and does not load the image back.

What options do I have to achieve this? Or do I have to load the image separately and present it in my own `UIImageView`?

**Comment by cgmaier** [comment]
hey @Kalvin126 ! thanks for catching this. 

to clarify, does the `url` contain an `.webp` (or `.gif`) file that's stored locally?

the `GPHMediaView` can only load images from remote urls, which may already be cached. this is definitely something we should make clear - sorry for the confusion! 
 
if you want to display a local file in an image view, you can use `GiphyYYAnimatedImageView`.  

if your goal is to persist a media object, you can also hang onto the `id` and use this approach: https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#media-ids

**Comment by Kalvin126** [comment]
The url, resolved from a `GPHMedia`, for example is `https://giphy.com/gifs/reaction-v0eHX3n28wvoQ". It is not local.

**Comment by Kalvin126** [comment]
Essentially, I save the Media's url to our backend database. when I fetch it, I need to present it again through a `GPHMediaView`. I can't save the Media's ID.

**Comment by cgmaier** [comment]
hey @Kalvin126, I think I understand now. 

To clarify, the `url` that you are saving is the `url` property of a `GPHMedia` object? This url is essentially just a link to the "detail page" for that GIF on GIPHY.com and can't be used by the `GPHMediaView`

The `GPHMediaView` can only show actual urls to `.webp` or `.gif` files. Grab an image url with the following code: 

`let url = media.url(rendition: .fixedWidth, fileType: .webp)`

you should the be able to use the `GPHMediaView`'s `loadAsset` function 

However, can you clarify why you can't save the media's ID as documented [here](https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#media-id)? this is our recommended approach for your use case.

**Comment by Kalvin126** [comment]
The image url may come from different sources so we just need to save a generic URL instead of a service specific ID.

The url with rendition and file type works! thanks! Closing issue.

**Comment by cgmaier** [comment]
That makes sense! thanks for the insight. we'll take note to better document this!

**Comment by Kalvin126** [comment]
Actually Could there be a completionHandler added to the `func loadAsset(at url: String, queueOriginalRendition: Bool = false)` function? or otherwise, how would I capture the error case?

**Comment by cgmaier** [comment]
hey @Kalvin126 sorry i missed this! feel free to reopen the issue or create a new issue in the future if you have additional comments so i can make sure i see it 

we can consider adding a completionHandler in a future release 

however, as it seems you like you want good deal of control over the image view, i recommend you make your own `GiphyYYAnimatedImageView` subclass, and handle the image request yourself. here's some example code that may help you. 

```
class AnimatedImageView: GiphyYYAnimatedImageView {
    weak var assetRequest: URLSessionDataTask?
    func loadAsset(url: String) {   
            assetRequest = GPHCache.shared.downloadAsset(url) { [weak self] (image, error) in
            self?.image = image
            self?.addAttribution()
            self?.assetRequest = nil 
        }
    }

}

```

let me know what you think!

**Comment by Kalvin126** [comment]
ok awesome that works!
