### ISSUE TITLE
Hiding the Watermark

### ISSUE THREAD

**Issue by Kalvin126** [Giphy/giphy-ios-sdk-ui-example#63]
Is it possible hide the water mark in a `GPHMediaView`?

**Comment by cgmaier** [comment]
hey @Kalvin126 it's not possible to hide the watermark. my comment on the other issue you opened should help you: 

https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/62#issuecomment-613044624

thanks!

**Comment by Kalvin126** [comment]
Thanks!
