### ISSUE TITLE
GiphyUISDK uses YYImage UIImage extensions, un-namespaced

### ISSUE THREAD

**Issue by beamPacer** [Giphy/giphy-ios-sdk-ui-example#67]
GiphyYYImageCoder.h includes the definitions for `UIImage (GiphyYYImageCoder)`, which are:
```
- (instancetype)yy_imageByDecoded;
@property (nonatomic) BOOL yy_isDecodedForDisplay;
- (void)yy_saveToAlbumWithCompletionBlock:(nullable void(^)(NSURL * _Nullable assetURL, NSError * _Nullable error))completionBlock;
- (nullable NSData *)yy_imageDataRepresentation;
```
While this category has been namespaced as `GiphyYYImageCoder`, and while the _classes_ implemented in this header are namespaced as `GiphyYY...`, these Objective-C selectors are not themselves namespaced and are therefore loaded in the Objective-C runtime as listed above (`yy_...`).

Unfortunately, YYImage defines these selectors identically, loading them into the table in the runtime for UIImage ([Link](https://github.com/ibireme/YYImage/blob/991b3397660ded73da362363f5d195862cfe0b3a/YYImage/YYImageCoder.h#L308)).

So, if an implementor has YYImage _and_ GiphyUISDK loaded up, the first lucky selector loaded at runtime gets called -- unknown to the caller, and unresolvable by Cocoapods's dependency management system. And if another SDK (or the client) has done the same thing as GiphyUISDK has done (included these selectors in their own `SomethingSomethingYYImage` without re-namespacing them), then you get the same problem, of course.

Ok! So that's what happened for us. We had `TextNowYYImage` as a pod, and included the Giphy SDK, and suddenly our pre-existing gif handling broke. We've just built in a fix by prefixing ours with `tnyy_...` etc., but it seems like the correct fix is for the Giphy SDK to prefix these, perhaps with `gphyy_...` or whatever makes sense. A more bulletproof solution would be to create a `GiphyUIImage` class and add class methods on it which are implemented with the contents of what's currently in the `yy_...` functions. Just some ideas! At the moment, this bug sort of sneaks in through the Objective-C runtime without one realizing what's happening.

**Comment by cgmaier** [comment]
hey @beamPacer thanks for your thorough post, great catch! I pushed a release 1.2.9 which resolves this issue. let me know if you have any issues with the update

**Comment by beamPacer** [comment]
Fantastic -- this is perfect. Thank you so much for your prompt response!
