### ISSUE TITLE
Unable to Initialize GiphyGridController Because No Public Initializers

### ISSUE THREAD

**Issue by LeeKahSeng** [Giphy/giphy-ios-sdk-ui-example#68]
Hi, I am getting following error when try to initialize `GiphyGridController`:
**Cannot invoke initializer for type 'GiphyGridController' with no arguments**

I am using 
- Giphy v1.2.7 
- Xcode v11.3.1
- CocoaPods v1.9.1

Please help. Thanks!

**Comment by cgmaier** [comment]
hey @LeeKahSeng thanks for catching this! i was able to reproduce and fix with v1.2.9 of the SDK. let me know if you have any issues with the upgrade. 1.2.8 came 


while the SDK does _not_ produce this error for Xcode 11.1 and Xcode 11.4, Xcode 11.3.1 seems to have a quirk! the fix for me was to just add this to the `GiphyGridController` class
```
    public convenience init () {
        self.init(nibName: nil, bundle: nil)
    }
```

**Comment by LeeKahSeng** [comment]
Hi @cgmaier thanks for the quick response, I am now able to initialize using v1.2.9. However, I do have to manually specify the podspec in my podfile in order to get v1.2.9. 
`pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.2.9/Giphy.podspec'`
Anyway, I will close the issue. Thanks a lot!

**Comment by cgmaier** [comment]
hey @LeeKahSeng ! thanks for confirmation.


 that's odd -- are you suggesting that 
```
pod 'Giphy'
```
and running `pod update` doesn't deliver `1.2.9`?

**Comment by LeeKahSeng** [comment]
Yup, when I use `pod 'Giphy'` I will get `1.2.7`. I think this already happening back when Giphy latest version is `1.2.8`.

**Comment by cgmaier** [comment]
hmm are you sure you're running `pod update` and not `pod install`? 

https://guides.cocoapods.org/using/pod-install-vs-update.html

**Comment by LeeKahSeng** [comment]
oops sorry, I am doing a clean installation, that's why I am running `pod install`.
