### ISSUE TITLE
ObjectiveC Example Build ERROR : -1: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'DeepDiff')

### ISSUE THREAD

**Issue by aiminh** [Giphy/giphy-ios-sdk-ui-example#7]
1.
ObjectiveC Example Build ERROR : -1: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'DeepDiff')

2. (Probably caused by 1)
giphy-ios-sdk-ui-example-master/Objective C/ExampleObjectiveC/ViewController.m:10:9: Could not build module 'GiphyUISDK'

**Comment by cgmaier** [comment]
Hey @aiminh what version of Xcode are you using? We are not supporting versions of Swift earlier than 5.0 at the moment (which requires Xcode `10.2` or later)

**Comment by aiminh** [comment]
I was using Xcode 10.1 !  Problem Solved! Thanks for the quick response!

**Comment by cgmaier** [comment]
Good to hear! Let us know if you encounter anything else.

**Comment by manjureddy48** [comment]
> I was using Xcode 10.1 ! Problem Solved! Thanks for the quick response!

what is the solution? I am facing same issue
