### ISSUE TITLE
Custom!

### ISSUE THREAD

**Issue by devny** [Giphy/giphy-ios-sdk-ui-example#71]
I have a question.
I want to create and reflect custom cells. Can I use GridViewController?? If not, I wonder if UICollectionViewCell can be overridden.

If all of the above methods do not work, I am wondering if I should implement them separately using the API.

**Comment by devny** [comment]
And there are additional questions.
I want to apply Cell's Background Color, but I don't think there are any related properties. How can I know how?

**Comment by cgmaier** [comment]
hey @devny thanks for opening this issue! check out [GPHTheme](https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#extending-gphtheme)

you should be able to override visual properties such as cell background color through that approach. 

what feature or behavior are you hoping to achieve by creating custom cells? accessing the `UICollectionView` / `UICollectionViewCell` directly isn't currently possible at the moment, unfortunately, but I'll pass your request to my team.

**Comment by devny** [comment]
@cgmaier 

Thanks for the answer.
I think you can override GPHTheme and use it.
There is another content that I want to custom. I am currently using GridViewController, but I want to apply CornerRadius to Cell. In the case of GPHMediaCell, it is not an open class, so override is not possible. How can I solve it?

**Comment by cgmaier** [comment]
@devny this is great feedback. I'll let my team know about your request - we can likely include corner radius property in a future release. in the meantime, can you think of any other properties you as a developer wish we supported? 

thanks for your help!

**Comment by devny** [comment]
@cgmaier Good morning. Here are some things that I think would be nice to add.
-loading placeholder Image: Image showing during loading
-cell corner Radius

I will write more comments when I think of it.

**Comment by devny** [comment]
@cgmaier 
And there are additional questions. I want to create GPHMedia and output it from GPHMediaView. I create GPHMedia using GPHMedia(id:String, type: GPHMediaType, url: String) and set the media in GPHMediaView, but it is not displayed in GPHMediaView.

let sampleMedia = GPHMedia(id, type: type, url: url)
mediaView.media = media

Please answer what to do.

**Comment by cgmaier** [comment]
hey @devny this feedback is really helpful! keep it coming :)  I think more customization of the `GPHMediaCell` per your suggestions should be manageable. 

as for the `GPHMedia` issue - it's possible we should make that constructor definition private, as  creating a `GPHMedia` object via that method isn't supported. here is the correct way to fetch a `GPHMedia` object from a media id: https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#media-ids

thanks again for all your feedback - appreciate your patience as it's a bit of a wild time in the world right now.

**Comment by devny** [comment]
@cgmaier Thank you for your help. When will the custom version above be released?
