### ISSUE TITLE
DeepDiff .swiftinterface file

### ISSUE THREAD

**Issue by beamPacer** [Giphy/giphy-ios-sdk-ui-example#72]
Hello!

The GiphyUISDK's .swiftinterface file specifies iOS 10 as the target version, which causes a problem with DeepDiff when the host's Podfile specifies `platform :ios, '11.0'`:

```Compiling for iOS 10.0, but module 'DeepDiff' has a minimum deployment target of iOS 11.0: [redacted]/Library/Developer/Xcode/DerivedData/[redacted]/Build/Products/Debug-iphonesimulator/DeepDiff/DeepDiff.framework/Modules/DeepDiff.swiftmodule/x86_64.swiftmodule```

We found a workaround after some puzzling over this (outlined below), which fixes it. But, I'm confused about why PinCache doesn't have this issue. The only difference I can grok is that DeepDiff's .xcconfig files have this line in them, which PinCache does not -- maybe there's a conflict between the baked-in .swiftinterface file which comes with the GiphyUISDK.framework, and this line from DeepDiff.

`OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS -suppress-warnings`

Another clue could be that before, we were using Xcode 11.3.1 and had iOS 11 as our deployment target; and all we changed here was upgrading to Xcode 11.5, same deployment target. So it very well may be that OTHER_SWIFT_FLAGS line that's the culprit here, under Xcode 11.5.

I'm just wanting to let you know that this was a very confusing error for us to hit in our upgrade to Xcode 11.5, and it might be worth adding a note to your README that the workaround is to add a build_settings edit to the Podfile post_install:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Whatever else you have in here...

            if target.name == 'DeepDiff'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end

            # Whatever else you have in here...
        end
    end
end
```

Assuming that the guess I make up above (about the problem being a conflict between DeepDiff's xcconfig files and GiphyUISDK's .swiftinterface file) is correct, maybe a better fix would be to contact the DeepDiff people, or maybe fork that yourself and fix it, or something. Sorry I can't be more specific with all of this but I thought this was a good point to hand the problem over to you, since a) we have a workaround, and b) further investigation would probably benefit from greater whitebox knowledge of your build pipeline, which you have and we don't :)

**Comment by cgmaier** [comment]
hey @beamPacer thanks for opening the issue - this is super helpful! will dig in and get back to you soon. 

I've never actually specified a platform version number in Podfile - as you can set a minimum iOS version in your target settings, what's the value in setting it here too?

**Comment by beamPacer** [comment]
The platform version number in the Podfile determines what deployment target version the Pods.xcodeproj gets set with, and then all of the pod targets within it get that as well. Otherwise, I think it just uses the minimum target it finds in any of the targets -- not _totally_ sure, but I think that's the default.

**Comment by nalexn** [comment]
Any update on this? If I set deployment target for `DeepDiff` to iOS 10, I get "Cannot load underlying module for 'DeepDiff'"

**Comment by cgmaier** [comment]
hey there @nalexn - apologies for the silence on this issue. haven't had a chance to do a deep dive into this. I'm not sure if the original issue description is still relevant -- 

what version of the GIPHY SDK are you using? 

the current min deployment target for the SDK is 10.2 - this was necessary to make the things compatible with future compiler versions

**Comment by nalexn** [comment]
The original description is relevant, though the message has slightly changed as DeepDiff's min deployment target has been bumped to 12.1 already.

GiphySDK SDK 2.0.3, Xcode 12.0.1

**Comment by cgmaier** [comment]
is it possible to share an example project which demonstrates this issue? I'm not able to reproduce.

**Comment by beamPacer** [comment]
@cgmaier , @nalexn -- here's a test project that shows the issue. This was created by creating a vanilla project using Xcode 12.0.1; integrating Cocoapods incl. `pod Giphy` into that existing project following the boring, normal steps [at this link](https://guides.cocoapods.org/using/using-cocoapods.html) and adding `platform :ios, '11.0'` to the top of the Podfile; running `pod install` like normal; opening the Cocoapods-created .xcworkspace file, and hitting Build in Xcode. Nothing fancy, and it demonstrates this error immediately, although to @nalexn 's point the error message has changed. It now says the two below messages in the build console. This is more helpful than the error message produced by Xcode 11.5, which is great! But it's the same underlying error :) Can we re-open this issue? I'm only making this request as a point of order really, because we already used the above workaround and we're fine, but it's still objectively an issue that others will bump into. _And_ because you're really great at responding to issues on this repository, and I want to be helpful! :)

/Users/emma.sinclair/REPOS/DeepDiffPodsIssueTester/Pods/Giphy/GiphySDK/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:5:8: Cannot load underlying module for 'DeepDiff'

/Users/emma.sinclair/REPOS/DeepDiffPodsIssueTester/DeepDiffPodsIssueTester/ViewController.swift:10:8: Failed to build module 'GiphyUISDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
