### ISSUE TITLE
ExampleObjectiveC needs updating to new `theme` API

### ISSUE THREAD

**Issue by beamPacer** [Giphy/giphy-ios-sdk-ui-example#73]
Just a note: the ExampleObjectiveC needs to be updated for the new API around GPHTheme -- this line causes compile issues:
https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Objective-C/ExampleObjectiveC/ViewController.m#L29

**Comment by cgmaier** [comment]
thanks for flagging this : )

**Comment by cgmaier** [comment]
this is fixed in 1.3.0 - thanks again!
