### ISSUE TITLE
didSelectMedia from GiphyUISDK.GiphyDelegate not called when used with GiphyUISDK.GiphySearchController

### ISSUE THREAD

**Issue by Dubnovitsky** [Giphy/giphy-ios-sdk-ui-example#75]
In my Swift application, I use **GiphyUISDK.GiphySearchController** which has a delegate property of **GiphyUISDK.GiphyDelegate** type.

Look at the next method declaration in **GiphyUISDK.GiphyDelegate**
`@objc func didSelectMedia(giphyViewController: GiphyUISDK.GiphyViewController, media: GiphyCoreSDK.GPHMedia)`

It uses **GiphyUISDK.GiphyViewController** which is not child or parent of **GiphyUISDK.GiphySearchController**. 

So the issue is **didSelectMedia** method is never called when **GiphyUISDK.GiphyDelegate** used with GiphySearchController

**Comment by cgmaier** [comment]
hey @Dubnovitsky ! Please _only_ use the `GiphyViewController`, rather than the `GiphySearchController`. See the example app in this repo for best practices. 

The `GiphySearchController` will be private in future versions of the SDK. hope this helps!

**Comment by Dubnovitsky** [comment]
@cgmaier, thanks for the clarification! So, probably I will use `GiphyGridController` with a custom search field and tabs

**Comment by cgmaier** [comment]
@Dubnovitsky if you are looking for customization options beyond what is available via the `GiphyViewController`, check out the `GiphyGridController` which is documented here: 

https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#grid-only-and-the-giphygridcontroller-setup
