### ISSUE TITLE
Multiple methods named 'theme' found with mismatched result

### ISSUE THREAD

**Issue by ezzz** [Giphy/giphy-ios-sdk-ui-example#80]
Dear Giphy team,

I thought I was about to display the Giphy HMI but not yet :)
I have an issue as soon as I import the Giphy SDK
like this 
`#import <GiphyUISDK/GiphyUISDK.h>`
or like this
`@import GiphyUISDK;`

As soon as I add the import line, I have the error on all my own `theme` var, used like this for instance:
`[[ThemeManager sharedManager] theme];`

Its definition is this one:
```
@interface ThemeManager : NSObject <LuminosityHandlerDelegate>  {
    Theme theme;
}

@property Theme theme;
```
Exact error is : Multiple methods named 'theme' found with mismatched result, parameter type or attributes
My theme variable is used like several hundred of times in multiple files so difficult to change my variable name for testing.

Any hint on how I could avoid this issue?

Thanks in advance

**Comment by cgmaier** [comment]
hey @ezzz that's very odd! searching around, it seems like people have fixed similar issues via casting i.e.`(Type*)` when referencing the var to disambiguate the type to the compiler. 

are there any other details you can share? what is the actual line of code which causes the error?

**Comment by ezzz** [comment]
hey @cgmaier 
indeed that's very odd
It surely is an issue on my side but as it appears as soon as I add the import line, maybe someone else already add that kind of issue

**Comment by ezzz** [comment]
Found the issue!
Indeed that was an issue related to the casting of my singleton : `[[ThemeManager sharedManager] theme];`
sharedManager was returning a generic `(id)` value instead of `ThemeManager*`
That was confusing the compiler with my theme attribute and the same attribute into GiphySDK: `@property (nonatomic, strong) GPHTheme * _Nonnull theme;`

Thanks for your hint on this

=> issue closed
