### ISSUE TITLE
After updating sdk getting error 

### ISSUE THREAD

**Issue by kumararun540** [Giphy/giphy-ios-sdk-ui-example#83]
I just updated sdk and getting error- 

[media urlWithRendition:GPHRenditionTypeFixedWidth fileType:GPHFileExtensionGif] 
error- No visible @interface for 'GPHMedia' declares the selector 'urlWithRendition:fileType:'
What I can use in place of this? 

For theme- 
giphy.theme = [[GPHTheme alloc] init];

its also not supporting now dart? is there any quick way to set theme dark?

**Comment by cgmaier** [comment]
hey @kumararun540 thanks for updating to the latest version ! there may be some issues with the Objective-C interfaces  - I'll take a look tomorrow : )

**Comment by kumararun540** [comment]
Ok @cgmaier Please let me know for the fix when you update it, we need to release by this week.

**Comment by cgmaier** [comment]
hey @kumararun540 sorry about the delay. this is fixed in the latest release 

there was an issue with the GPHThemeType Objective-C interface, which is now fixed. to set the theme to dark you can do: 
```
giphy.theme = [[GPHTheme alloc] init];
giphy.theme.type = GPHThemeTypeDark;
```

as for obtaining the assets you can do: 
``` 
NSString *url = media.images.fixedWidth.gifUrl ;
NSString *url = media.images.fixedWidth.webPUrl ; 
```

**Comment by kumararun540** [comment]
@cgmaier Thanks for quick update, all working now :)
