### ISSUE TITLE
How to hide search suggestions?

### ISSUE THREAD

**Issue by tonite31** [Giphy/giphy-ios-sdk-ui-example#85]
I don't want to show the search suggestions bar to users of my app. This is because this bar displays unwanted languages ​​such as Chinese.

I want an option to hide this bar.

**Comment by cgmaier** [comment]
hi @tonite31 this is now possible with the latest release: https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.0.2
