### ISSUE TITLE
Cannot build after disabling use_frameworks

### ISSUE THREAD

**Issue by gilbertl** [Giphy/giphy-ios-sdk-ui-example#86]
According to https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/35, we should be able to use this library without use_frameworks. 

However, I tried it just now and the build fails with

```
Cannot load underlying module for 'DeepDiff'
Failed to load module 'GiphyUISDK'
```

Here's my fork: https://github.com/gilbertl/giphy-ios-sdk-ui-example

I'm on XCode 11.6

**Comment by cgmaier** [comment]
hey thanks for resurfacing this @gilbertl - it must have broken again

**Comment by cgmaier** [comment]
im going to close this issue as I reopened #35
