### ISSUE TITLE
Disabling Search

### ISSUE THREAD

**Issue by paulxuca** [Giphy/giphy-ios-sdk-ui-example#88]
Is there a way to disable the search bar?

**Comment by cgmaier** [comment]
hey @paulxuca ! you can achieve this with the [GiphyGridController](https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#grid-only-and-the-giphygridcontroller-setup)

**Comment by paulxuca** [comment]
@cgmaier Thanks for the response! Is there a easy way to use the `GiphyViewController` and still be able to disable/ hide the search bar?
