### ISSUE TITLE
GiphyViewController mismatch mediaType tabs

### ISSUE THREAD

**Issue by mmdock** [Giphy/giphy-ios-sdk-ui-example#89]
Using `GiphyViewController`

`giphy.mediaTypeConfig = [.gifs, .recents, .stickers, .emoji, .text]
`

when the viewcontroller is full screen we see that all 5 options show at the bottom:
![IMG_3492](https://user-images.githubusercontent.com/2423465/91901681-722abc00-ec55-11ea-9c59-86601c4ea95b.PNG)

but when I am typing, I only see 3 tabs.  I understand maybe causing recents to go away, but why emoji as well?
![IMG_3491](https://user-images.githubusercontent.com/2423465/91901989-dcdbf780-ec55-11ea-881e-238135c595fc.PNG)

**Comment by cgmaier** [comment]
hey @mmdock - the reason `emoji` and `recents` disappear when search is initiated is because those categories aren't "searchable", currently.  

this has been a source of confusion in the past, and so we will take a look at how it could be more clear.
