### ISSUE TITLE
function didSelectMedia return wrong media type

### ISSUE THREAD

**Issue by binodav** [Giphy/giphy-ios-sdk-ui-example#91]
Giphy version: 2.0.1

`func didSelectMedia(giphyViewController: GiphyViewController, media: GPHMedia) {`
      `   //always return "gif" value` 
      `   let mediaType = media.type.rawValue`       
`}`

Is there anyway to get the correct media type  "gif", "stickers", "emoji" ? The function above always return "gif". Thank you.

**Comment by cgmaier** [comment]
I'll look into this - thanks!

**Comment by binodav** [comment]
@cgmaier Sorry, I just want to clarify this issue only happens when I select from "Recents" tab.

**Comment by cgmaier** [comment]
hey @binodav this should be fixed in the latest release:
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.0.5
