### ISSUE TITLE
Occasional crash when selecting Gifs

### ISSUE THREAD

**Issue by mmdock** [Giphy/giphy-ios-sdk-ui-example#92]
When adding in using the SDK for giphy into my application, I was occasionally encountering this crash:

<img width="924" alt="giphy crash 2" src="https://user-images.githubusercontent.com/2423465/92161397-738aee80-ede5-11ea-9d4c-91ba9aa7dc65.png">

<img width="629" alt="giphy crash" src="https://user-images.githubusercontent.com/2423465/92161388-6ec63a80-ede5-11ea-9fca-ad2b035915f3.png">

I had seen it occur on 12.4, 13.5, and iOS 14 simulators.  
Giphy 2.0.1 sdk.
current code implementation in my app below.
What was happening: giphy would sometimes crash as I select a gif.  It is not easy to produce, but happened at least 3 different occasions while I was testing out giphy.

<img width="808" alt="Screen Shot 2020-09-03 at 12 12 18 PM" src="https://user-images.githubusercontent.com/2423465/92161814-02980680-ede6-11ea-9df0-c632c4524626.png">

**Comment by cgmaier** [comment]
thanks for sharing this @mmdock - would it be possible to share a sample application?

**Comment by mmdock** [comment]
@cgmaier i can try, but as i stated above, it isn't easy to reproduce.  there isn't a reliable repro case

**Comment by cgmaier** [comment]
hey @mmdock are you still experiencing this crash? any additional details you can provide?

**Comment by mmdock** [comment]
@cgmaier  it still happens, but only occasionally and while I am attached to the debugger / opened by running via Xcode.  I am unable to make it happen in a Testflight build.  Usage of Giphy SDK has been released in my application for about a week now and there have been no Production crashlogs that look like this that I can see

**Comment by cgmaier** [comment]
thanks for the follow up @mmdock
