### ISSUE TITLE
How to change layout to carousel mode

### ISSUE THREAD

**Issue by ASM-Anik** [Giphy/giphy-ios-sdk-ui-example#93]
I was trying to add giphy sdk to my custom keyboard for iPhone and i would like to change the layout to carousel mode.
i have a button on my keyboard that will trigger the giphy view controller. can anyone suggest how I can set the view controller above my keyboard in carousel mode. 
Sorry if it seem like a no brainer question but i'm new at this and any help would be very helpful.

**Comment by cgmaier** [comment]
hey @ASM-Anik ! The `GiphyViewController` setup won't work in keyboard extensions. Please check out the `GiphyGridController` section of the docs.

**Comment by ASM-Anik** [comment]
Thanks for the suggestion
