### ISSUE TITLE
PINCache unrecognized selector

### ISSUE THREAD

**Issue by Morniak** [Giphy/giphy-ios-sdk-ui-example#95]
Hi, 

When presenting the `GiphyViewController`, I'm getting the following crash: 

```
-[PINCache setObject:forKey:withAgeLimit:]: unrecognized selector sent to instance 0x282606eb0
2020-09-15 14:57:40.796676+0200 YOLO[1414:936943] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PINCache setObject:forKey:withAgeLimit:]: unrecognized selector sent to instance 0x282606eb0'
```

I think it might be related to conflicting version of PINCache since another of my pods is using it. 

Here is simplified version of my Podfile.lock: 

```
PODS:
  - Giphy (2.0.2):
    - DeepDiff
    - libwebp
    - PINCache
  - PINCache (2.3)
  - SnapSDK/SCSDKBitmojiKit (1.6.3):
    - PINCache (< 3.1, >= 2.3)
    - PINOperation (~> 1.1)
  - SnapSDK/SCSDKCreativeKit (1.6.3)
  - SnapSDK/SCSDKLoginKit (1.6.3)

DEPENDENCIES:
  - Giphy
  - SnapSDK/SCSDKBitmojiKit
  - SnapSDK/SCSDKCreativeKit
  - SnapSDK/SCSDKLoginKit

SPEC REPOS:
  trunk:
    - PINCache
    - PinLayout
    - PINOperation

SPEC CHECKSUMS:
  PINCache: ce36ed282031b92fc7733ffe831f474ff80fddc2
  PinLayout: 0d96022e46e8b80468d819f182a393b97ca038da
  PINOperation: 3a967a927e7867e61976c6cc23e5770416449fbc
  SnapSDK: ea1ed6ebec009ab63027a91afcb02047135b86bc


PODFILE CHECKSUM: d4a67a2e5c8cf43edd03dd1a99d9f41fcc20fd43

COCOAPODS: 1.9.3
```

I'm getting this crash on iOS 13.7 & 12.0

**Comment by Morniak** [comment]
Update: I made a project with the bug. It's not a conflict with different PINCache version as I thought since I am able to reproduce the crash just with the Giphy SDK. 

https://github.com/Morniak/YUNoWorkGiphy

Just put an api key, run and you should get the crash.

**Comment by cgmaier** [comment]
hey thanks @Morniak ill look into this

**Comment by cgmaier** [comment]
hey @Morniak im going to revert to an older version of PINCache

**Comment by cgmaier** [comment]
hey @Morniak this should work:

**Comment by Morniak** [comment]
I'm using 
``` 
 pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.1/Giphy.podspec'
```
since the 2.0.3-Xcode-12 version don't compile on my side (I'm working on XCode 11.7). It fix the crash but I'm getting another issue. The `GPHMediaView` do not display anything when setting a media instantiated by myself. I updated the repo with this issue (https://github.com/Morniak/YUNoWorkGiphy/blob/master/YUNoWorkGiphy/ViewController.swift).
