### ISSUE TITLE
Unable to build with Giphy on Xcode 12

### ISSUE THREAD

**Issue by drewolbrich** [Giphy/giphy-ios-sdk-ui-example#96]
Using Xcode 12 GM, I'm unable to build against GiphyUISDK. I get the following errors:

```
/Users/drew/Repos/Grizzy/Pods/Giphy/GiphySDK/GiphyUISDK.framework/
Modules/GiphyUISDK.swiftmodule/arm64-apple-ios.swiftinterface:5:8: 
Compiling for iOS 10.0, but module 'DeepDiff' has a minimum deployment 
target of iOS 12.0: /Users/drew/Library/Developer/Xcode/DerivedData/
Trash-bxabdlnwfmgvwsdglfuqpydusfbm/Build/Products/Development
-iphoneos/DeepDiff/DeepDiff.framework/Modules/DeepDiff.swiftmodule/
arm64-apple-ios.swiftmodule

/Users/drew/Repos/Grizzy/Trash/Clips/ClipsViewController.swift:11:8: 
Failed to build module 'GiphyUISDK' from its module interface; the 
compiler that produced it, 'Apple Swift version 5.1 (swiftlang-
1100.0.270.13 clang-1100.0.33.7)', may have used features that 
aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang
-1200.0.29.2 clang-1200.0.30.1)'
```

I'm confused about the "Compiling for iOS 10" part, because everywhere in my project I'm explicitly specifying 12.1 as the deployment target.

I tried updating my Podfile post_install handler to explicitly set `IPHONEOS_DEPLOYMENT_TARGET`, but no dice.

Is there any obvious solution to this I'm overlooking?

**Comment by cgmaier** [comment]
hey @drewolbrich going to download the GM. in the meantime, can you share your Podfile?

**Comment by drewolbrich** [comment]
Hi @cgmaier thank you for responding. 

I had the same issue with the previous version of Xcode 12 beta, but I did not have time to investigate it then. The issue is not unique to the GM.

Our Podfile is here: http://traipse.com/giphy/Podfile.txt 
(please don't judge 😄 )

The Giphy reference is down near the bottom.

If I remove the `pod 'Giphy'` line from the Podfile and remove all references to Giphy in our source code, then the app builds correctly as expected. Although, it now occurs to me that when I did that earlier today, I believe I also had to manually remove references to Giphy and the frameworks that Giphy references.

Let me know if there is anything else you need or would like me to try.

**Comment by tmspzz** [comment]
This happens if the deployment target is >= 13.4

**Comment by drewolbrich** [comment]
> This happens if the deployment target is >= 13.4



> [GiphyXcode12Error.zip](https://github.com/Giphy/giphy-ios-sdk-ui-example/files/5233283/GiphyXcode12Error.zip)
> 
> Here's minimal sample project reproducing the issue.

Thank you.

**Comment by drewolbrich** [comment]
> This happens if the deployment target is >= 13.4

fwiw my project's deployment target is 12.1.

**Comment by cgmaier** [comment]
can you guys try this? compiled with Xcode 12 compiler:

```
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec'
```

**Comment by drewolbrich** [comment]
> can you guys try this? compiled with Xcode 12 compiler:
> 
> ```
> pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec'
> ```

@cgmaier I am in the middle of juggling something else, maybe for 1/2 hour, but I will try that immediately after I'm done.

**Comment by kaandedeoglu** [comment]
@cgmaier This didn't work for us. We also had to run it through a modified local podspec since PINCache 3.1.0 doesn't exist on trunk yet.

**Comment by tmspzz** [comment]
We also tried manually integrating the previous version & using carthage. Both seems to work. This might be a Cocoapods issue.

**Comment by cgmaier** [comment]
ok gotcha. not sure what happened with PINCache `3.1.0` - as that version is causing issues for people, I may revert to a prior version and specify limitations in the Podspec. thanks for your patience!

**Comment by cgmaier** [comment]
thanks guys - I just updated the podspec here: 

```
pod 'Giphy', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec'
```

be sure to run this first! 
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by drewolbrich** [comment]
@cgmaier I tried adding Giphy via `https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec` as you posted above and clearing my CocoaPods cache and Pods directory, and running `pod update Giphy`, and I still see the same errors: (btw I'd rather not run a full `pod update` because that would update all the other pods we're including)

![Screen Shot 2020-09-16 at 11 35 35 AM](https://user-images.githubusercontent.com/12141562/93378476-5dcbef00-f811-11ea-8188-1b4ffb44c5e9.png)

![Screen Shot 2020-09-16 at 11 35 24 AM](https://user-images.githubusercontent.com/12141562/93378484-60c6df80-f811-11ea-9f3c-de0172bf1561.png)

What version of Xcode are you using to build GiphyUISDK?

**Comment by tmspzz** [comment]
@drewolbrich  I don't think it's picking up the correct binary. Are you sure you're not including, say 1.3.0 ?

**Comment by cgmaier** [comment]
<img width="507" alt="Screen Shot 2020-09-16 at 12 02 28 PM" src="https://user-images.githubusercontent.com/11489602/93380800-915c4880-f814-11ea-8f67-77c1330b89a4.png">
it works with 13.3 target deployment info - but when I bump up to 13.4 I get compile error, though different than those noted above. 

seems similar to this issue, if not the same one:
https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/77

**Comment by cgmaier** [comment]
hey all - have an update! believe some aspect of these issues has to do with the extra architectures included in build process to support simulators for apple silicon Macs. 

some discussion here: 
https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/96

this works for me now for deployment targets below & above 13.4
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update Giphy
```

**Comment by kaandedeoglu** [comment]
@cgmaier The instructions above did fix the issue here, amazing, and thanks for the quick investigation ⭐ 🥂 Can we expect you to make this into an official Podspec soon?

**Comment by cgmaier** [comment]
very much appreciate the speedy confirm. yes I will push an official release shortly

**Comment by tmspzz** [comment]
@cgmaier can you elaborate on how the issue is connected to the extra simulator arch for  Apple Silicon Macs?

**Comment by drewolbrich** [comment]
@cgmaier This is working for me now using the podspec on AWS.

I had to take Xcode outside and have a stern conversation with it, but ultimately it came around.

**Comment by drewolbrich** [comment]
@cgmaier Also, thank you !!! 😄

**Comment by cgmaier** [comment]
hey @tmspzz I pasted the wrong link following `some discussion here: ` - https://github.com/Carthage/Carthage/issues/3019

my high level understanding of the issue is that Xcode 12s command line build process produces duplicate architectures in order to support simulators on the new Apple Silicon macs (arm) which create conflicts. I believe the solution provided in the above thread is to exclude those Apple Silicon simulator architectures. 

this whole ordeal reaffirms the value of SPM / .xcframework support https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/49

**Comment by drewolbrich** [comment]
@cgmaier If you don't can, please post here when the next official release is available.

**Comment by PureBreadd** [comment]
We have a bunch of other Pods in our Podfile and when after running the recommended commands above, we end up with a bunch of new errors ("duplicate architecture symbols", among others). If we uninstall all Pods and then reinstall all Pods, it removes all of our new errors, but the original error from this chain still persists. Please let us know when the official updated release is available for the Giphy pod!

**Comment by drewolbrich** [comment]
@cgmaier I have been using `https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec` for the last week and it's working great, thank you.

However, I just discovered that in the simulator, it only appears to work for debug builds.

Non-debug builds fail with this error:

![Screen Shot 2020-09-23 at 11 09 16 AM](https://user-images.githubusercontent.com/12141562/94052011-3a62f000-fd8d-11ea-9db3-cf51e936abd4.png)

I see this error when building for the simulator for iOS 12, 13, and 14.

I tried deleting DerivedData and deleting the Cocopods cache and Pods directories and running `pod update giphy` and the issue persisted.

Non-debug builds do work fine on the device, so that is a workaround for the short term.

**Comment by cgmaier** [comment]
hey all, I've finally pushed an official release here https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.0.3

**Comment by cgmaier** [comment]
@drewolbrich I am seeing another workaround here: https://github.com/Carthage/Carthage/issues/3019#issuecomment-698895501

**Comment by KrisConrad** [comment]
@cgmaier when using the official v2.0.3 sdk my app crashes now after presenting the GiphyViewController. It looks like the crash is happening somewhere in PINCache.

When using the podspec linked in previous comments the crash does not happen. It looks like that pod spec is installing PINCache 2.3 where the official one installs v2.0.

**Comment by drewolbrich** [comment]
@cgmaier 
> @drewolbrich I am seeing another workaround here: [Carthage/Carthage#3019 (comment)](https://github.com/Carthage/Carthage/issues/3019#issuecomment-698895501)

Thank you, this worked beautifully.

**Comment by cgmaier** [comment]
hey @KrisConrad my apologies for the late reply. this is now fixed in 2.0.4.

**Comment by KrisConrad** [comment]
> hey @KrisConrad my apologies for the late reply. this is now fixed in 2.0.4.

Awesome, thanks!

**Comment by VittoriDavide** [comment]
Hi @cgmaier,

I am building with Xcode 12.2, and Giphy version 2.0.7 and I am having a the same issue this time for swift version 5.3.1

Failed to build module 'GiphyUISDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

**Comment by sourceSoftTauseef** [comment]
> @cgmaier I have been using `https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec` for the last week and it's working great, thank you.
> 
> However, I just discovered that in the simulator, it only appears to work for debug builds.
> 
> Non-debug builds fail with this error:
> 
> ![Screen Shot 2020-09-23 at 11 09 16 AM](https://user-images.githubusercontent.com/12141562/94052011-3a62f000-fd8d-11ea-9db3-cf51e936abd4.png)
> 
> I see this error when building for the simulator for iOS 12, 13, and 14.
> 
> I tried deleting DerivedData and deleting the Cocopods cache and Pods directories and running `pod update giphy` and the issue persisted.
> 
> Non-debug builds do work fine on the device, so that is a workaround for the short term.

Hello cgmaier this command is not working in my mac

**Comment by sourceSoftTauseef** [comment]
its giving the issue like this 
 Failed to fetch podspec for `Giphy` at `https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/2.0.3-Xcode-12/Giphy.podspec`.
 Error: 403 Forbidden

**Comment by aemre** [comment]
any update
