### ISSUE TITLE
Clearing the search field does not clear the search results

### ISSUE THREAD

**Issue by beamPacer** [Giphy/giphy-ios-sdk-ui-example#99]
Entering text into the search text field changes the gif results to match that search; but if you hit the little ⓧ button in the search field, the search results stick around. I made a gif of this happening using Giphy Capture :) Sorry about the slightly potato quality, I was trying to keep the file size below 10Mb.

![giphy-search-issue](https://user-images.githubusercontent.com/1409593/94297276-1d5b2800-ff19-11ea-97b9-99b10401c2ac.gif)

**Comment by cgmaier** [comment]
nice catch @beamPacer will look at this soon 🥇

**Comment by cgmaier** [comment]
hi @beamPacer this is fixed in the latest release: 
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.0.5
thanks!
